name: preview
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.1
  animations: ^2.0.11
  flutter_custom_clippers: ^2.1.0
  flutter_svg: ^2.1.0
  provider: ^6.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/